debug: true

exporter:
  type: console
  batchSize: 10
  capacity: 10000
  endpoint: "http://localhost:8080/collect"

instrumentation:
  executor: true
  jdbc: false
  httpClient: false
  scheduled: false
  timing: true
