debug: true

exporter:
  type: console
  batchSize: 10
  capacity: 10000
  endpoint: "http://localhost:8080/collect"

instrumentation:
  executor:
    enabled: true
  jdbc:
    enabled: false
  httpClient:
    enabled: false
  scheduled:
    enabled: false
  timing:
    enabled: true
    entrypoints:
      - "ir.myhome.spring.controller.*"
      - "ir.myhome.spring.service.*"
